// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlewqdGXCxRYsBgNNVDmV2bklxqCW5yRA',
    appId: '1:336083712982:web:c8b5b4cc2bdfc0db630277',
    messagingSenderId: '336083712982',
    projectId: 'todoapp-50c4d',
    authDomain: 'todoapp-50c4d.firebaseapp.com',
    storageBucket: 'todoapp-50c4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1LHkX9ESAOGh3XOs8sJiLkNwLo4iXrk',
    appId: '1:336083712982:android:e46756f2e238a4ae630277',
    messagingSenderId: '336083712982',
    projectId: 'todoapp-50c4d',
    storageBucket: 'todoapp-50c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Hn86EbxauF-7DC3dRCW5szTWDioRjp8',
    appId: '1:336083712982:ios:df7ccdbc6a89543a630277',
    messagingSenderId: '336083712982',
    projectId: 'todoapp-50c4d',
    storageBucket: 'todoapp-50c4d.appspot.com',
    iosClientId: '336083712982-4kcbfkv43a4nlc23aml7j365t8oor5qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
